### ISSUE TITLE
Dressrosa Not Processing

### ISSUE THREAD

**Issue by godver3** [JakeLunn/one-pace-plex-assistant#14]
The Dressrosa arc doesn't seem to process correctly:
- Skipping [One Pace] Chapter 702-703 [720p][E058DEF9].mkv as it does not match expected name format.
- Please ensure that the original file name has not been changed!
- Extracting episode information from file: [One Pace] Chapter 704-705 [720p][90034ECC].mkv

**Comment by krustykrabpiza** [comment]
i had the same issue, the dressrosa arc has a different naming scheme than all of the others. I had to go and rename all of the episodes to the correct naming scheme with PowerRename and some manual changes and then the script worked as intended

**Comment by Jov3nlzw** [comment]
> The Dressrosa arc doesn't seem to process correctly:
> 
> * Skipping [One Pace] Chapter 702-703 [720p][E058DEF9].mkv as it does not match expected name format.
> * Please ensure that the original file name has not been changed!
> * Extracting episode information from file: [One Pace] Chapter 704-705 [720p][90034ECC].mkv



> i had the same issue, the dressrosa arc has a different naming scheme than all of the others. I had to go and rename all of the episodes to the correct naming scheme with PowerRename and some manual changes and then the script worked as intended

Any of you guys can lep me with the issue i reported? I am struggling TT

**Comment by krustykrabpiza** [comment]
> > The Dressrosa arc doesn't seem to process correctly:
> > 
> > * Skipping [One Pace] Chapter 702-703 [720p][E058DEF9].mkv as it does not match expected name format.
> > * Please ensure that the original file name has not been changed!
> > * Extracting episode information from file: [One Pace] Chapter 704-705 [720p][90034ECC].mkv
> 
> > i had the same issue, the dressrosa arc has a different naming scheme than all of the others. I had to go and rename all of the episodes to the correct naming scheme with PowerRename and some manual changes and then the script worked as intended
> 
> Any of you guys can lep me with the issue i reported? I am struggling TT

Don't really have anything that can help besides just saying you need to rename the episodes by hand. Look at the naming scheme of the other seasons and copy that format to all the dressrosa episodes. took me maybe 30 mins with PowerRename and some manual work and the script worked as expected

**Comment by Jov3nlzw** [comment]
I have a tip for u guys if this happens again use this tool called bulk rename utility it can match what u want to rename and do it one shot

But what i meant was i have a seperate issue i reported but i guess ill post it here as well. If the issue is that i have one piece and one pace in the same library then i will swap it

Episode title not showing in plex for Wano 33 - wano 38 and egghead 1 - egghead 2

Every other episode title is working fine.
when running the comment this happens.

C:\Windows\System32>oppa setup-plex -t "vwoTmKbkFD2Cg_T4akMC" -ph "http://localhost:32400/web/" -l "Anime" --one-piece-show-name "One Pace"
Traceback (most recent call last):
File "main.py", line 97, in
File "main.py", line 90, in main
File "modules\plex.py", line 55, in run
File "plexapi\server.py", line 116, in init
File "plexapi\server.py", line 764, in query
File "xml\etree\ElementTree.py", line 1338, in XML
xml.etree.ElementTree.ParseError: mismatched tag: line 33, column 2
[19468] Failed to execute script 'main' due to unhandled exception!

Please send help

**Comment by Jov3nlzw** [comment]
> > > The Dressrosa arc doesn't seem to process correctly:
> > > 
> > > * Skipping [One Pace] Chapter 702-703 [720p][E058DEF9].mkv as it does not match expected name format.
> > > * Please ensure that the original file name has not been changed!
> > > * Extracting episode information from file: [One Pace] Chapter 704-705 [720p][90034ECC].mkv
> > 
> > 
> > > i had the same issue, the dressrosa arc has a different naming scheme than all of the others. I had to go and rename all of the episodes to the correct naming scheme with PowerRename and some manual changes and then the script worked as intended
> > 
> > 
> > Any of you guys can lep me with the issue i reported? I am struggling TT
> 
> Don't really have anything that can help besides just saying you need to rename the episodes by hand. Look at the naming scheme of the other seasons and copy that format to all the dressrosa episodes. took me maybe 30 mins with PowerRename and some manual work and the script worked as expected



> I have a tip for u guys if this happens again use this tool called bulk rename utility it can match what u want to rename and do it one shot
> 
> But what i meant was i have a seperate issue i reported but i guess ill post it here as well. If the issue is that i have one piece and one pace in the same library then i will swap it
> 
> Episode title not showing in plex for Wano 33 - wano 38 and egghead 1 - egghead 2
> 
> Every other episode title is working fine. when running the comment this happens.
> 
> C:\Windows\System32>oppa setup-plex -t "vwoTmKbkFD2Cg_T4akMC" -ph "http://localhost:32400/web/" -l "Anime" --one-piece-show-name "One Pace" Traceback (most recent call last): File "main.py", line 97, in File "main.py", line 90, in main File "modules\plex.py", line 55, in run File "plexapi\server.py", line 116, in init File "plexapi\server.py", line 764, in query File "xml\etree\ElementTree.py", line 1338, in XML xml.etree.ElementTree.ParseError: mismatched tag: line 33, column 2 [19468] Failed to execute script 'main' due to unhandled exception!
> 
> Please send help

**Comment by JakeLunn** [comment]
The new file naming format throws a bit of a wrench into the way this application works. It removed the title, arc name and episode number from the filename and left only the manga chapters, so I'm currently rewriting the tool to match based on manga chapters. In the meantime, using PowerRename like @krustykrabpiza suggested is a good idea as a workaround. 

> I have a tip for u guys if this happens again use this tool called bulk rename utility it can match what u want to rename and do it one shot
> 
> But what i meant was i have a seperate issue i reported but i guess ill post it here as well. If the issue is that i have one piece and one pace in the same library then i will swap it
> 
> Episode title not showing in plex for Wano 33 - wano 38 and egghead 1 - egghead 2
> 
> Every other episode title is working fine. when running the comment this happens.
> 
> C:\Windows\System32>oppa setup-plex -t "vwoTmKbkFD2Cg_T4akMC" -ph "http://localhost:32400/web/" -l "Anime" --one-piece-show-name "One Pace" Traceback (most recent call last): File "main.py", line 97, in File "main.py", line 90, in main File "modules\plex.py", line 55, in run File "plexapi\server.py", line 116, in init File "plexapi\server.py", line 764, in query File "xml\etree\ElementTree.py", line 1338, in XML xml.etree.ElementTree.ParseError: mismatched tag: line 33, column 2 [19468] Failed to execute script 'main' due to unhandled exception!
> 
> Please send help

This error suggests an issue with parsing the XML that your Plex server is returning. I'll see if I can recreate it.

**Comment by Jov3nlzw** [comment]
Thank you, Please let me know if you have a fix for me cause to be honest i have zero idea how all this works, it took me so long to figure out how to use the set up media and then even longer for the issue i reported.

> The new file naming format throws a bit of a wrench into the way this application works. It removed the titles from the filename and left only the manga chapters, so I'm currently rewriting the tool to match based on manga chapters. In the meantime, using PowerRename like @krustykrabpiza suggested is a good idea as a workaround.
> 
> > I have a tip for u guys if this happens again use this tool called bulk rename utility it can match what u want to rename and do it one shot
> > But what i meant was i have a seperate issue i reported but i guess ill post it here as well. If the issue is that i have one piece and one pace in the same library then i will swap it
> > Episode title not showing in plex for Wano 33 - wano 38 and egghead 1 - egghead 2
> > Every other episode title is working fine. when running the comment this happens.
> > C:\Windows\System32>oppa setup-plex -t "vwoTmKbkFD2Cg_T4akMC" -ph "http://localhost:32400/web/" -l "Anime" --one-piece-show-name "One Pace" Traceback (most recent call last): File "main.py", line 97, in File "main.py", line 90, in main File "modules\plex.py", line 55, in run File "plexapi\server.py", line 116, in init File "plexapi\server.py", line 764, in query File "xml\etree\ElementTree.py", line 1338, in XML xml.etree.ElementTree.ParseError: mismatched tag: line 33, column 2 [19468] Failed to execute script 'main' due to unhandled exception!
> > Please send help
> 
> This error suggests an issue with parsing the XML that your Plex server is returning. I'll see if I can recreate it.
